### ISSUE TITLE
test suite should include some GPU tests

### ISSUE THREAD

**Issue by adam-m-jcbs** [BoxLib-Codes/Microphysics#15]
To my knowledge, the PGI test suite doesn't do any tests that utilize the GPU.  I recommend adding a test using the `ignition_simple` network, `BS` integrator, and the GPU (`ACC=t`).  Something along the lines of:

```
$ cd $MICROPHYSICS_HOME/networks/ignition_simple/test
$ make COMP=PGI ACC=t
$ ./testburn.Linux.PGI.debug.acc.exe
```

Something like this should serve as a minimal verification that basic GPU code is working.  As more integrators and/or networks are robustly utilizing the GPU, we can add similar tests to test them (in this case, the default GNUMakefile has already chosen the `BS` integrator for us).

**Comment by zingale** [comment]
ignition_simple with VBDF was added
