### ISSUE TITLE
Basic GPU test fails

### ISSUE THREAD

**Issue by adam-m-jcbs** [BoxLib-Codes/Microphysics#16]
The basic GPU test described in Issue #15 fails.  On my local machine, I get

```
[ajacobs@xrb test](development *)$ ./testburn.Linux.PGI.acc.exe

 Initializing Helmholtz EOS and using Coulomb corrections.

FATAL ERROR: data in update device clause was not found on device 1: name=pi
 file:/home/ajacobs/Codebase/Microphysics/networks/ignition_simple/test/../../../EOS/helmholtz/actual_eos.F90 actual_eos_init line:1327
```

On Stony Brook's `bender`, I get what may be an error in the system configuration:

```
[ajacobs@bender test](development)$ ./testburn.Linux.PGI.acc.exe 
 
 Initializing Helmholtz EOS and using Coulomb corrections.
 
modprobe: FATAL: Module nvidia-uvm not found in directory /lib/modules/4.7.5-200.fc24.x86_64
call to cuInit returned error 999: Unknown
```

The error happens with and without debug symbols.

The error seems to be saying `pi` isn't initialized, but in `actual_eos.F90` it is declared.  I'm investigating the error now.

**Comment by zingale** [comment]
bender was a driver issue.  Reinstalling the drivers fixed it.

Adam's machine seems to be a pascal GPU issue -- too new?

**Comment by adam-m-jcbs** [comment]
Initial tests suggest the PGI compilers have a bug that I've seen before with OpenACC and linking.  

First, I was able to eliminate the above error by setting the default CUDA to 8.0.  To do this, you can add `set DEFCUDAVERSION=8.0;` to your `/opt/pgi/linux86-64/16.9/bin/localrc` file.  Once I do that, the error changes from the above to a build error:

```
$ make COMP=PGI ACC=t
<lots of make output>
<link line>
nvlink error   : Undefined reference to '_eos_type_module_24' in 'testburn.o'
nvlink error   : Undefined reference to '_actual_network_16' in 'testburn.o'
nvlink error   : Undefined reference to '_actual_eos_module_24' in 'testburn.o'
nvlink error   : Undefined reference to '_actual_eos_module_16' in 'testburn.o'
nvlink error   : Undefined reference to '_screening_module_24' in 't/Linux.PGI.debug.acc/o/actual_rhs.o'
nvlink error   : Undefined reference to '_screening_module_16' in 't/Linux.PGI.debug.acc/o/actual_rhs.o'
nvlink error   : Undefined reference to '_extern_probin_module_24' in 't/Linux.PGI.debug.acc/o/actual_rhs.o'
nvlink error   : Undefined reference to '_bs_type_module_16' in 't/Linux.PGI.debug.acc/o/integrator.o'
pgacclnk: child process exit status 2: /opt/pgi/linux86-64/16.9/bin/pgnvd
/home/ajacobs/Codebase/BoxLib/Tools/F_mk/GMakerules.mak:25: recipe for target 'testburn.Linux.PGI.debug.acc.exe' failed
make: *** [testburn.Linux.PGI.debug.acc.exe] Error 2
```

If I move object files around on the link line such that dependencies come first, then the undefined reference errors start to go away.

I'm going to do further testing and consult with PGI support to confirm that this is a compiler bug.

**Comment by adam-m-jcbs** [comment]
The issue appears to be purely a function of the ordering of the object files on the link line.  This should be a compiler bug.  I've alerted PGI.  A workaround is to manually order the object files on the link line.  If the error persists, it could be worthwhile to add some functionality to the build system to order object files based on the dependencies.

As the bug isn't in our code, I'm marking the issue closed.
